-- create the tables

create table product_category (
	id integer generated by default as identity,
	name varchar(255) not null,
	description varchar(255),
	primary key (id)
);

create table supplier (
	id integer generated by default as identity,
	name varchar(255) not null unique,
	primary key (id)
);

create table customer (
	id integer generated by default as identity,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	username varchar(255) not null unique,
	password varchar(255) not null,
	email_address varchar(255) not null unique,
	primary key (id)
);

create table product (
    id integer generated by default as identity,
    description varchar(255),
    image_url varchar(255),
    name varchar(255) not null,
    price decimal(19,2) not null,
    weight double,
    category_id integer,
    supplier_id integer,
    primary key (id)
);

create table location (
    id integer generated by default as identity,
    city varchar(255),
    country varchar(255),
    county varchar(255),
    street_address varchar(255),
    name varchar(255) not null,
    primary key (id)
);

-- had to name this orderr because apparently order is a keyword and I wasn't allowed to use it
create table orderr (
    id integer generated by default as identity,
    city varchar(255),
    country varchar(255),
    county varchar(255),
    street_address varchar(255),
    created_at timestamp not null,
    customer_id integer,
    location_shipped_from_id integer,
    primary key (id)
);

create table order_detail (
    id integer generated by default as identity,
    quantity_id integer not null,
    order_id integer,
    product_id integer,
    primary key (id)
);

create table revenue (
    id integer generated by default as identity,
    date date not null,
    sum decimal(19,2) not null,
    location_id integer,
    primary key (id)
);

create table stock (
    id integer generated by default as identity,
    quantity integer not null,
    location_id integer,
    product_id integer,
    primary key (id)
);

-- add the constraints

alter table order_detail 
add constraint FK_orderdetail_orderr
foreign key (order_id) 
references orderr;
    
alter table order_detail 
add constraint FK_orderdetail_product
foreign key (product_id) 
references product;
    
alter table orderr 
add constraint FK_orderr_customer
foreign key (customer_id) 
references customer;
    
alter table orderr 
add constraint FK_orderr_locations
foreign key (location_shipped_from_id) 
references location;
    
alter table product 
add constraint FK_product_productcategory
foreign key (category_id) 
references product_category;
    
alter table product 
add constraint FK_product_supplier
foreign key (supplier_id) 
references supplier;
    
alter table revenue 
add constraint FK_revenue_location
foreign key (location_id) 
references location;
    
alter table stock 
add constraint FK_stock_location
foreign key (location_id) 
references location;
    
alter table stock 
add constraint FK_stock_product
foreign key (product_id) 
references product;
